rmit-s3666814-yujue-zou/Assignment2

src/Classmate.java
src/Colleague.java
src/Relationship.java

Create new class

---

src/Adults.java
src/Children.java
src/Person.java

Add person class
Add Adults class
Add Children class

Add person class

---

src/Adults.java
src/Children.java
src/Person.java

Refactor person to use extends

Refactor person to use extends

---

src/Couple.java
src/Friends.java
src/Parent.java

create couple, friends,parent class

---

src/Classmates.java
src/Colleagues.java
src/Couple.java
src/Friends.java
src/Parent.java
src/Relationship.java

update classmates/colleagues/couple/friends,relationship.
Delete class parent

update several classes

---

src/Driver.java

- deploy hsqldb into the project
- create people table
- finish addPeople method

addPeople DB function

---

src/Relationship.java

create class relationship

---

src/Driver.java
src/MiniNet.java
src/PeopleDao.java

Read data from DB when MiniNet runs

Tom-person-05

---

src/MiniNet.java
src/Relationship.java
src/RelationshipDao.java

create RelationshipDao, update Relationship/MIniNEt

create RelationshipDao, update Relationship/MIniNEt

---

src/MiniNet.java
src/RelationshipDao.java

- Launch People and relationship read data from txt file.
- Apply them to functionality “3) Display the profile” and “6) Define
relation between two people”

Tom-MiniNet-01

---

src/Driver.java
src/MiniNet.java
src/PeopleDao.java

Hotfix - Exception crash the program while the program load data from
database

Tom-person-06

---

src/Adults.java
src/Children.java
src/MiniNet.java
src/NoAvailableException.java
src/NoParentException.java
src/NoSuchAgeException.java
src/NotToBeClassmatesException.java
src/NotToBeColleaguesException.java
src/NotToBeCoupledException.java
src/NotToBeFriendsException.java
src/Person.java
src/TooYoungException.java
src/YoungChild.java

Add 1 class: YoungChild for who is under age of 2.
Add 8 Exception subclasses: They extend from class Exception
Add 1 Attribute: String RelationshipList at Person class to record
relations related to this person.

Tom-Exception-01

---

src/MiniNet.java

Implement function no.2
"2) Select a person”

Tom-MiniNet-03

---

src/Driver.java
src/MiniNet.java

Clean code

---

Relationship.txt
src/Driver.java
src/GUI.css
src/MiniNet.java

Complete Functionality items
- 5) Find out whether two people are directly connect in some ways
- 6) Define relation between two people
- 7) Find out the name(s) of the children or parents

Tom-MiniNet-04

---

src/Driver.java
src/MiniNet.java

Implement Functionality
7) Find out the name(s)of a person’s child(ren) or the names of the
parents

Tom-MiniNet-05

---

src/Driver.java
src/MiniNet.java
src/PeopleDao.java

Final edition before submission 17/05/2018 11.57pm

Tom-MiniNet-06

---

src/MiniNet.java
src/NoSuchAgeException.java

- Test NoSuchException
- Implement default Gender as male
- Can only define friends, colleagues, classmates
- When define relationship, you can only insert people in this network

Tom-Exception-02

---

People.txt
src/MiniNet.java
src/PeopleDao.java

- Complete Exception No Such Age Exception
- Add one more test data as Susan Turner in both DB and text file.
- Catch SQLSyntaxErrorException to show if read from DB failed, print
out Stack Trace and System.exit(0)

Tom-Exception-03

---

src/Driver.java
src/MiniNet.java
src/NoSuchAgeException.java
src/PeopleDao.java
src/TooYoungException.java

Tom-clean-code-02
- clean code and clean the error msgs
- implements the exception of Too Young Exception (When user define
relationship, if one of the people are less than 3 years old, show
error message.)

Tom-clean-code-02

---

src/Driver.java
src/MiniNet.java
src/NotToBeCoupledException.java

- Implement Not to be coupled Exception
1. If one of them are not adults
2. If one of them has already been taken
3. If they are both males or both females

Tom-Exception-04

---

src/MiniNet.java
src/NotToBeFriendsException.java

Implements exception
- Not to be friends Exception
- Not to be colleagues Exception
- Not to be classmates Exception

Tom-Exception-05

---

src/RelationshipDao.java

Tom-RelationshipDao-01

---

src/Driver.java
src/MiniNet.java
src/NotToBeFriendsException.java
src/PeopleDao.java
src/RelationshipDao.java

Format and follow the coding standard

Tom-clean-code-04
